### ISSUE TITLE
make "Courier New Bold.ttf" the default font (font field left blank) for w3d

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#100]
@wphicks Will: I think this may be my confusion. Let's talk tomorrow if at all possible for you ...

@wphicks Let's keep working on this. I used update.sh late Monday (I did *not* do a reinstall) and I get the error below (when trying to run a file in the shared Google Drive samples folder). I can copy the ttf into the folder but 1) I shouldn't have to do this and 2) the name is ambiguous (if this file is actually the bold version of Courier New that we should be using, and 3) the software is not grabbing the font as actually pre-installed in my system (perhaps you want to be copying this font the root directory of any xml file that has blank font fields?)

Blender quit
INVOCATION >> /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender --background --python /Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py -- desktop /Users/kongqi/GDrive/BrownGDrive2013/Courses/Writing3D/Writing3D_XML_Samples/sample_09_fontlights.xml
found bundled python: /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/../Resources/2.76/python
Traceback (most recent call last):
  File "/Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py", line 61, in <module>
    my_project = project.W3DProject.fromXML_file(args.project_file)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 426, in fromXML_file
    ET.parse(filename).getroot(), call_directory)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 334, in fromXML
    new_project["objects"].append(W3DObject.fromXML(child))
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 1045, in fromXML
    new_object["content"] = W3DContent.fromXML(node)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 366, in fromXML
    return W3DText.fromXML(content_root)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 534, in fromXML
    new_text["font"] = text_root.attrib["font"]
  File "/Users/kongqi/W3D/Writing3D/pyw3d/features.py", line 84, in __setitem__
    value, key, self.argument_validators[key].help_string))
pyw3d.errors.InvalidArgument: Courier_New.ttf is not a valid value for option font
Additional Info: Could not find file /Users/kongqi/GDrive/BrownGDrive2013/Courses/Writing3D/Writing3D_XML_Samples/Courier_New.ttf
W3D Configuration loaded from /Users/kongqi/.w3d.json
Configuration information:  {'Blender player executable': '/Users/kongqi/W3D/blender/blenderplayer.app/Contents/MacOS/blenderplayer', 'Export script path': '/Users/kongqi/W3D/Writing3D/pyw3d/w3d_export_tools.py', 'Blender executable': '/Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender'}

Blender quit

**Comment by wphicks** [comment]
@shadoof Yeah, my apologies; I don't think I was clear yesterday. I've got the patch available but haven't actually pushed it yet. I'm available all day today, so ping me at your convenience. Until then, I'm going to work on improving the update scripts to make it easier to grab bleeding-edge and non-release versions for testing.

**Comment by shadoof** [comment]
@wphicks Thanks Will, no real worries. There is a lot going on for me just now but I hope to be in chat with you this afternoon. Priority for me is to make sure all the students have a working version of the new local renderer. It's a good group and I am hopeful that they will be able work with us to launch w3d properly.

**Comment by wphicks** [comment]
No problem. I can work on plenty of other things in the meantime. For students having trouble installing or running w3d, please don't hesitate to have them email me.

**Comment by wphicks** [comment]
@shadoof If you like the changes from [v0.2.4](https://github.com/wphicks/Writing3D/tree/v0.2.4), please feel free to go ahead and close this.

**Comment by shadoof** [comment]
Happy with this ...
