### ISSUE TITLE
Mac sometimes misidentified as Linux during install

### ISSUE THREAD

**Issue by wphicks** [wphicks/Writing3D#101]
Based on feedback from @shadoof on an error some students encountered when attempting to run cwapp.py, some Mac systems are being misidentified as Linux during install, resulting in a bad path for the Blender executable being written to .w3d.json.

I really need the output of `platform.system()` on an affected machine to drill down on this, but I'll see if I can scare anything up through research.

**Comment by shadoof** [comment]
@wphicks Sorry Will, my system's not affected so I can't help with the specifics above. Have any of the students been able to help. I presume that .w3d.json could be edited directly. If so, myself or the new code-savy DLA 1st year, Sally Chen Qianxun  <address@email.com> could help students until this ticket is closed. Please invite Sally to the repo. Github handle: cqx931

**Comment by wphicks** [comment]
Yes, Olivia has contacted me (with a delightfully thorough bug report), and I've been going back and forth with her. You're absolutely correct about the workaround, and I'll post exactly what needs to be done here in just a bit (trying to set up a couple of other things first).

@cqx931: Great to meet you, Sally! We're doing everything via fork-and-pull, so you probably won't need collaborator access for anything (and I see you've already forked). If you have an interest in getting more involved with the project, though, it would certainly be welcome! Drop me an email if you want to chat.

**Comment by wphicks** [comment]
Ooh! Just realized (based on an email from @cqx931) that the problem was occurring earlier than I realized. The *real* issue is in findblender.sh, which was blindly copied from Linux to Mac. Fixing it up now and pushing a patch.

**Comment by wphicks** [comment]
Confirmed solved by 76960689d4c95ac3afade981a1aa5aef01a65bdf.
