### ISSUE TITLE
potential developer/testers need better access to the log produced by CWEditor.jar

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#103]
* it would be good to be able to open this log from an agreed place in the folder hierarchy
* optionally, it would be good to be able to clear the log while running the editor

**Comment by wphicks** [comment]
Right, this should actually be very straightforward if we know where we want to put the logs. I'll just redirect the output in the various cwapp scripts. Possible places to put the log:
1. A dedicated W3D workspace directory (e.g. ~/w3d_workspace) that could then also serve as a place to store automated backups of XML projects.
2. In the same directory as the .xml
3. In the parent directory of the Writing3D repo (my least favorite option).

Opinions?

**Comment by shadoof** [comment]
I favor option 1.

**Comment by wphicks** [comment]
@shadoof If you like the changes from d90fd62b9a65ccb33009f0258066dc8f737468cc, please feel free to go ahead and close this.

**Comment by shadoof** [comment]
Tested. Works for me (although only from command line on Macs – the editor reconfirmed as stripping out the <Debug> tag).
