### ISSUE TITLE
positioning: w3d renderer positions text objects differently depending on whether 'Around self-axis' is set to true

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#104]
whereas CW renderer does not.
* reproduce using samples__0_start_button.xml, turning 'bigO's self-axis on or off
* may only effect positioning on the y-axis but needs checking

**Comment by wphicks** [comment]
Roger that. I'll check it out ASAP. Thanks for the instructions to reproduce!

**Comment by wphicks** [comment]
I'm able to reproduce this and understand the cause. My tentative fix introduced another problem, though, so I may not get this taken care of for a couple days.

**Comment by wphicks** [comment]
Resolved by 831c6556cb707f4d51b5377de135510a218188f1
