### ISSUE TITLE
relative rotation in the new Blender-based renderer has easing in and out built-in?

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#109]
I think this is the case, but is not the case in the CW renderer.

Observe the effects in the 'sample_17_rotation.xml' recently pushed to the samples_debugging branch of w3d_samples, *but note*, the problem of starting one timeline perhaps starting all timelines will have to be addressed first.

**Comment by wphicks** [comment]
Sorry, what exactly do you mean by easing in and out?

**Comment by shadoof** [comment]
@wphicks Easing in: acceleration of rotational speed at the beginning of the movement and, easing out: deceleration at the end (non-linear speed of rotation, such that when one rotation is immediately followed by another there is seems to be a brief pause in between, which may not be desirable: currently I can't think of a way to get an object to spin 360 degrees and keep spinning).

**Comment by wphicks** [comment]
Ah, right. I see what you mean, and I think I know how to take care of it. I'll get to work on it as soon as I can.

**Comment by shadoof** [comment]
@wphicks This is one that should be sensitive to the version (cw / w3d) flag.

**Comment by shadoof** [comment]
@wphicks I have radically simplified samples_17_rotation in w3d_samples/samples_debugging to demo the two features that are different with respect to w3d and CW rendering:
* CW rotates with axes on the front surface of the word's model (w3d in the model center - flag needed as above)
* w3d introduces easing in and easing out at the beginning and end of relative movements whereas relative movements in CW are linear

(Thus smooth, linear rotation of objects can be quite easily achieved in CW but not yet in w3d.)

**Comment by wphicks** [comment]
Thanks very much for the simplified example! Exactly what I needed. I'll see what I can do.
