### ISSUE TITLE
name of 'fonts' folder (at the same level as <main>.xml file) should not be case sensitive

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#111]
'Fonts' and 'FONTS' in particular should be OK (enough for now)

**Comment by shadoof** [comment]
@wphicks Hi Will, maybe I could use this at my initial 'way in' to the actual code. I've had a look and imagine that tweaks to either validators.py or objects.py could be made to accommodate alternative path names, but I don't have codeable tweak as yet. Do you have quik guidance?

**Comment by wphicks** [comment]
Wonderful! Thanks for hopping in on this one. The key line is right [here](https://github.com/wphicks/Writing3D/blob/efc50facab1fb3af5ec0d4cac634d881ee6ffb82/pyw3d/objects.py#L576). It's probably best to check whether [either directory exists](https://docs.python.org/3.6/library/os.path.html#os.path.isdir) and if so look for the font inside it.

**Comment by shadoof** [comment]
@wphicks hi Will, my first attempt at actually addressing the code. (First python also so, be gentle. ;) Please advise on any workflow adjustments I should make.

**Comment by wphicks** [comment]
Fixed by @shadoof's PR #114. Many thanks!
