### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by purvigoel** [wphicks/Writing3D#20]
Terminal Output:

  "Module bpy not found. Loading "
/Users/purvigoel/Writing3D/pyw3d/activators/triggers/links.py:28: UserWarning: Module bpy not found. Loading pyw3d.timeline as standalone
  "Module bpy not found. Loading pyw3d.timeline as standalone")
/Users/purvigoel/Writing3D/pyw3d/objects.py:42: UserWarning: Module bpy not found. Loading pyw3d.objects as standalone
  "Module bpy not found. Loading pyw3d.objects as standalone")
/Users/purvigoel/Writing3D/pyw3d/groups.py:29: UserWarning: Module bpy not found. Loading pyw3d.actions as standalone
  "Module bpy not found. Loading pyw3d.actions as standalone")
/Users/purvigoel/Writing3D/pyw3d/project.py:41: UserWarning: Module bpy not found. Loading pyw3d.objects as standalone
  "Module bpy not found. Loading pyw3d.objects as standalone")

OS Version: 10.9.2

**Comment by purvigoel** [comment]
result after attempting to import pyw3d in a python3 terminal:

/Users/purvigoel/Writing3D/pyw3d/activators/triggers/look_triggers.py:29: UserWarning: Module bpy not found. Loading pyw3d.activators.triggers.look_triggers as standalone
  "Module bpy not found. Loading "
/Users/purvigoel/Writing3D/pyw3d/activators/triggers/links.py:28: UserWarning: Module bpy not found. Loading pyw3d.timeline as standalone
  "Module bpy not found. Loading pyw3d.timeline as standalone")
/Users/purvigoel/Writing3D/pyw3d/objects.py:42: UserWarning: Module bpy not found. Loading pyw3d.objects as standalone
  "Module bpy not found. Loading pyw3d.objects as standalone")
/Users/purvigoel/Writing3D/pyw3d/groups.py:29: UserWarning: Module bpy not found. Loading pyw3d.actions as standalone
  "Module bpy not found. Loading pyw3d.actions as standalone")
/Users/purvigoel/Writing3D/pyw3d/project.py:41: UserWarning: Module bpy not found. Loading pyw3d.objects as standalone
  "Module bpy not found. Loading pyw3d.objects as standalone")

result after trying to import pyw3d in blender:

bpy.obps.text.run_script()
Python script fail, look in the console for now...

**Comment by wphicks** [comment]
Hmmm... Looks like the new version from develop didn't actually get installed. Just as a sanity check, can you go to the directory you installed from and run
`git show`
and check that the commit number at the top is 77e3c0bee76150baf2c233e152de69829e24ac3b?

**Comment by purvigoel** [comment]
I think you're right, as the number is:

commit 13146d300a25cd3785c23601f50af89697e3d7cd

I will try to install it again!

**Comment by wphicks** [comment]
Ah, righto! You're on the master branch. Use `git checkout develop` to switch to the develop branch and see what you get.

**Comment by purvigoel** [comment]
I get:

M   pyw3d/**init**.py
M   sitecustomize.py
Already on 'master'
Your branch is up-to-date with 'origin/master'.

**Comment by wphicks** [comment]
Oh, sorry! I originally said `git checkout master` but it should be `git checkout develop` (editied above). When you get a second, let's take this to IM and I'll walk you through the details.

**Comment by wphicks** [comment]
Closing this issue following successful testing with 77e3c0b.
