### ISSUE TITLE
Movement relative to walls currently not working

### ISSUE THREAD

**Issue by wphicks** [wphicks/Writing3D#24]
We should figure out how to sensibly support movement relative to walls for legacy compatibility. The original sample_image.xml is a good test project for this.

**Comment by wphicks** [comment]
@purvigoel: This might be a good one for you to take a look at if you have interest. The issue is that movement relative to the walls is a bit of an anachronism (Oculus headset obviously has no walls to move relative to), so I didn't put too much effort into this.

We should really make this such that movements relative to walls just add a vector specifying wall position to each movement. We'll need to do a similar thing for rotations, but that's a bit trickier. Want to take a crack at this? Or we can work on it together, or you can do something else entirely.

**Comment by purvigoel** [comment]
Ah, I see! I'll take a crack at this and try to figure it out. If I can't quite nail it down, we could work on it together, if that's good?

**Comment by wphicks** [comment]
Sounds great! Just let me know how things go.

**Comment by purvigoel** [comment]
I'm having a bit of trouble figuring this out. I understand what we're trying to do, and I think two of the pertinent blocks of code are in placement.py: def _create_relative_to_objects() and place(). I think _create_relative_to_objects() handles movements relative to the walls to be used in place(). If that's right, then should a change should be made in place() so that the output of _create_relative_to_objects() counts only as a vector? I'm a bit stuck, so if you have a chance, I think it would be fun to tackle this together! Let me know what you think!

**Comment by wphicks** [comment]
Sure, why don't you hit me up on IM whenver you want to tackle this?

The short response is that you're on the right track but need to look at one other place in the code. _create_relative_to_objects will create EMPTY objects (Blender placeholders essentially) at the places indicated for the walls. Think of those as storage for the placement information that relative placements require.

place deals with the _initial_ placement of objects, and if you look at lines 270 and 276, you'll see that it already appropriately modifies location and rotation based on the placement of the walls.

What we're really interested in is movements _after_ the initial placement. That will take place between lines 155 and 175 of pyw3d/blender_actions/movement.py. Here, we generate a script that will be used by the Blender Game Engine (BGE) to perform the actual movement. Notice that nowhere in there do we check for the "relative_to" setting of self.placement. So, we'll need to check that, look up the position of the wall, and add a vector accordingly.

Note that lines 156-164 cover "relative movement," which is to say movement relative to the objects current position. This is a separate thing from movement relative to a wall. Note also that the schema (and legacy cwapp) currently allows relative movement that is relative to the wall. This is clearly undefined behavior (can't be relative to two points at the same time), so we'll need to make a decision about how we want to handle that case.

**Comment by wphicks** [comment]
Resolved by 798bd8851783cb14e13ec2465cc25ff7de34c9c3
