### ISSUE TITLE
Text Rotation Issue

### ISSUE THREAD

**Issue by purvigoel** [wphicks/Writing3D#29]
We noticed in sample.xml that the moving text did a 180 degree rotation as it moved to the Right Wall, after the user clicked "Fly Right." I put in debug statements in movement.py, in the start string, continue string, and end string to track rotation. Sure enough, for the Front Wall, Left Wall, and Floor Wall, there was no indication of rotation. For the Right Wall, however, the debug statement in "continue_string" was:

2016-07-18 09:47:17,310    DEBUG W3D activate called on link_object_rightlink with status Continue
2016-07-18 09:47:17,310    DEBUG W3D ROTATION FOUND: Rotation present in continue string
2016-07-18 09:47:17,326    DEBUG W3D activate called on link_object_rightlink with status Continue
2016-07-18 09:47:17,326    DEBUG W3D ROTATION FOUND: Rotation present in continue string
2016-07-18 09:47:17,343    DEBUG W3D activate called on link_object_rightlink with status Continue

And for end_string, I printed the rotation vector, angle, and up vector, for:

2016-07-18 09:47:17,343    DEBUG W3D Rotation Status: LookAt with vector [0.0, 0.3048, 0.0] and angle 0
2016-07-18 09:47:17,343    DEBUG W3D Up vector is: [0.0, 0.0, 0.3048]

So the rotation status was LookAt for the Right Wall only, which I believe was causing the rotation. I looked at sample.xml, and sure enough, in the script for "right link", there's the following code:

 Placement
                         RelativeTo RightWall /RelativeTo
                                   Position (0.0, 0.0, 0.0) /Position
                                             LookAt target="(0.0, 0.0, -1.0)" up="(0.0, 1.0, 0.0)" 
/Placement

I tried removing the LookAt target line and ran sample.xml again. There was no more weird rotation. So my guess was that the LookAt line was the "problem"--if it was a problem. I can imagine that the line was deliberately added so that the moving text could still be read when it was on the Right Wall, rather than existing as a mirror image of the original text (the text starts on the Left Wall, so having no rotation wouldn't be readable if it was plastered in the same orientation on the Right Wall).

**Comment by purvigoel** [comment]
I created a test example in CWEditor.jar for rotation. It seems like, in general, rotation of text moving from wall to wall is a built-in functionality. That is, I don't have to make any LookAt changes when creating the links for the text to rotate to preserve its orientation. A rotation of moving text occurs at every wall.

However, in cwapp.py, the rotation occurs only at the Right Wall because of the LookAt script. So I'm guessing that it's one of those rotation things which is built-in for the CWEditor.jar but not the cwapp.py

**Comment by wphicks** [comment]
Ah, right. It's very odd and annoying that that sample has rotation specified for just one movement. Let's correct that once we get permission to post those samples. In the meantime, the larger issue is what I've now described in #31, which we were aware of previously. Going to close this issue, and further discussion can take place on #31.
