### ISSUE TITLE
error reporting for missing and other font issues

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#46]
fonts referenced by xml that cannot be found break the preview without informative error reporting

**Comment by wphicks** [comment]
@purvigoel, if you have an extra second, would you mind running a project with a missing font and sending me whatever the current error we get is?

**Comment by purvigoel** [comment]
Sure! I've stuck a picture of one of the error messages to this post.

<img width="1280" alt="screen shot 2017-02-08 at 9 51 36 pm" src="https://cloud.githubusercontent.com/assets/20029387/22767367/d3f72d7e-ee48-11e6-8720-28e35a081577.png">

**Comment by wphicks** [comment]
Awesome! Thanks very much. This should be an easy fix; it looks like it's just using the generic error message for a bad feature choice. So, we can override that for fonts and other assets.

**Comment by wphicks** [comment]
Resolved by e38e93f2b5e970507d2241b7a10f78b4b798949a.
