### ISSUE TITLE
Change version number and/or window title for the old GUI cweditor.jar

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#51]
... in order to easily distinguish it from another copy on a developer's system that is targeting the *old* previewer. (e.g. so I can tab-toggle back and forth comparing behavior on my system.)

**Comment by wphicks** [comment]
Sadly, this is trickier than it ought to be. I think we'd have to recompile the jar with JaxFront using the latest version of the editor source, and I'm not certain anyone knows where that is at this point. I quite agree that this would be helpful, but I don't think it's possible without a lot of digging. I'm going to close this for now, but please feel free to reopen it if this is a major priority or if you have some insight on how to make it happen.
