### ISSUE TITLE
sample_01_first.xml - issues listed:

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#53]
1. (problem, already ticketed) old engine only works with "./fonts/<fontname>" so before opening in an editor targeting the new engine, all "./" prefixes must currently be removed.
2. (context) this sample has been rescripted so all positions are center-relative. movements are absolute.
3. (problem) link clicking does not work in the new engine as expected and as in the old
4. (problem) the old schema allowed 'numbers' of clicks (one or more). 'Any' is the default and should be supported. Currently changing 'Any' to a number of clicks *breaks* the XML for the w3d (not the cw) engine.
5. (problem) under the w3d engine and clicking through first time round, the text goes to the correct locations *except when returning to the left wall* but the angle specs for "around self axis" (set to 'yes') are wrong (complementary 90 = 270?), and ...
6. (problem) second time round, clicking through, locations are haywire?
7. (problem) the rendering of (automatic) text models (especially with depths), in terms of their response to light is very different in w3d. we need to address the "(responds to) Lighting:" parameter in the old cw schema and perhaps also the fact that objects under the old cw engine gave off their own *ambient* light (I believe)

**Comment by wphicks** [comment]
For my own reference, Problem 1 here is #52. Will investigate everything here further ASAP. @purvigoel, if you're available, investigating exactly what the deal is with Problem 3 would be useful.

**Comment by shadoof** [comment]
@wphicks @purvigoel, sample__first.xml renamed to sample_01_first.xml

**Comment by wphicks** [comment]
Recording the issue that each of these corresponds to before closing:
1. #52 
3. #56 
4. #56 
5. #61 
6. #68
7. #64
