### ISSUE TITLE
Scaling of text different from legacy CW

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#54]
"Desktop Starting Camera Position" seems to have no effect on the W3D blender previewer and, in any case, the default  X, Y, Z for this and ALSO, crucially, for "Cave Starting Camera Position" should be:
X: 0, Y: 1.5; Z: (at least) 6.0

I also think that allow-rotation and allow-movement should both default to "Yes" in W3D.

**Comment by shadoof** [comment]
More generally: there is something - particularly in terms of how changing the Z parameter (for 'camera/tracked' position is very different for the CW and W3D (desktop) previewers. CW does a good job of showing what will be seen in the Cave (currently); W3D seems (for example) to place the camera too close to text objects which may also be differently *scaled* ('scale' parameter for objects also needs checking)
- NB: this is based on working through the old samples

**Comment by wphicks** [comment]
About to make appropriate changes to defaults. @purvigoel, I could use some help in updating samples accordingly.

@shadoof, getting the "scales" to match is absolutely an issue. The scalings for both systems are in (essentially) arbitrary units. Would you mind trying to tweak the scale for some example until it looks about right to you and let me know by what factor you had to tweak? Once we have that, I can refine from there. Importantly, this should ultimately be based on actual measurements within the CAVE to account for all possible scaling effects.

**Comment by shadoof** [comment]
@wphicks @purvigoel, As I think Will knows, I am working through the samples in the shared folder:
Writing3D_XML_Samples and I have already changed all the xml files in this folder to have these new global defaults. I am making all the samples ready so that they *in principle* should work under W3D

**Comment by wphicks** [comment]
Ah, sorry. I was actually referring to the python-based samples, which will have to be updated to bring things up to eye-level.

**Comment by wphicks** [comment]
Latest commit should address everything here except the scaling issue, which will require more testing. @shadoof, if everything but the scaling works out, please feel free to close this, and I'll open a new issue for scaling.

**Comment by shadoof** [comment]
@wphicks, This clearly needs more research, and I've only looked at text, but *IF* the camera position is the same (distance from object) is the same for both systems then *for text* (images not yet checked) a scale of 3 in CW looks the same if it is adjusted to a scale of 2 in W3D. (How to do this accurately??)

**Comment by wphicks** [comment]
Great, thanks very much. It should (fortunately) be the same scaling factor for both images and text, I think. To get this very accurate (and make sure we're not leaving anything out), we'll have to actually look at it in the Cave, where there's a genuine physical scale.

**Comment by shadoof** [comment]
@wphicks @purvigoel Right. So this will be the big one. Can we already run the same projects under both CW and W3D in the Granoff Cave (at least)? You haven't yet - have you Will? - tried to install W3D on the Granoff machines?

**Comment by wphicks** [comment]
No I haven't yet. It would probably be best for me to come down in person or to talk someone through this over Skype. I'm also going to try to install this in the RPI CAVE in the next week or so, which should help me work out some kinks.

**Comment by wphicks** [comment]
From here on, this issue will be used for discussion of scaling issues around text. For image scaling, see #67, and for camera starting position, see #62.

**Comment by wphicks** [comment]
Merging #60 with this.

**Comment by wphicks** [comment]
Addressed by 46602b1011e415. Please reopen if scaling is not precise enough for any legacy project.
