### ISSUE TITLE
Look for fonts in "fonts" folder if not found elsewhere

### ISSUE THREAD

**Issue by wphicks** [wphicks/Writing3D#55]
It would be useful to have cwapp.py look for a fonts folder in the same directory as the xml if it can't find the desired font.

**Comment by wphicks** [comment]
@shadoof, I'm implementing this now, but would you mind keeping an eye out for how often this actually gets used by people in class and/or your own work? Doing this requires that we use a separate validation scheme for font files and regular files, and I'm worried that we may confuse some people with this. i.e. "You mean I can just specify the path to the font file, or does it always need to be relative to a fonts folder? Do I have to have a fonts folder? It works if I don't put it in a fonts folder, so why do I need a fonts folder? Why does the error message not say that it was looking in the fonts folder? Why does the error message say it *was* looking for a fonts folder?"

If this does turn out to be confusing, we'll just roll it back.

**Comment by shadoof** [comment]
Understood @wphicks but then people do expect fonts, generally, to be treated differently with respect to other resources so I think this is a reasonable exception. Question: if there is only a font name (no path) in the xml and the resources themselves are not in a folder but are found the same level as the xml, will this now (also) work? (Ideally, I think, this coding should work if the font resources are either at the level of the xml or in a fonts folder, unless this is a major hassle for you, in which case *must be in a fonts folder* if full path not given).

**Comment by wphicks** [comment]
Last commit should have addressed this fully. We now look for fonts relative to the xml file and relative to a "fonts" directory in the same directory as the fonts file. Only after looking for a file in BOTH locations and failing will validation or a Blender build fail. Let me know if there's anything you want tweaking on, @shadoof.

**Comment by wphicks** [comment]
Oh, and good point about people expecting fonts to be treated differently. I think that's actually absolutely true, and I'm now much more on board with this.
