### ISSUE TITLE
Links improperly triggered for overlapping objects

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#56]
This sample will be a good one to work on exhaustively in order to sort:
* the way links work in W3D, current issues:
  * click (number of) parameters not clear and not working as expected with 'Any' default
  * enabled parameter and enable color not working
  * stay on parameter and stay on color needs checking
* scaling is 0.666 the correct factor for W3D scaling? how to determine this?
* around self axis parameter and rotation for all objects

**Comment by shadoof** [comment]
separating link issues from scaling. This will be for links. run and compare samples 02 and 02alt. Both work fine in CW. Behaviors have a variety of issues in W3D. The following things need sorting:
* Click through (default to 'yes' in W3D!)
* Number(s) of clicks
* Make sure that object links are disabled whenever they are made invisible/faded out.

**Comment by wphicks** [comment]
Oh, bullet 3 is a bit of a surprise, actually. Doesn't the old system allow clicking of invisible links? I thought that was a feature that several projects make use of in significant ways.

**Comment by shadoof** [comment]
Bullet 3: I'm pretty sure we allowed and used the clicking of invisible (transparent) *image* objects but not invisible *text* objects. (The original xml for samples 01 - 02 demonstrates, I think, that under the old system text objects that are faded out do not respond to clicks - they were set to stay enabled and they were not disabled in the link actions.

**Comment by wphicks** [comment]
Okay, I've just confirmed that *all* links are currently deactivated when invisible. This will need to be changed for images to ensure legacy compatibility, but that can spin off to a separate issue.

The issue here is with how Blender handles mouse-over events with invisible objects (Not well!). So, we need to switch to a raycasting system of our own that will properly handle the clickthrough property. Going to see if I can get that done now, but leaving this note in case this gets delayed.

**Comment by wphicks** [comment]
Use samples 02 and 02alt for testing

**Comment by wphicks** [comment]
I'm actively working on this, but it may be a few days before the fix goes through. I think this is the highest priority issue right now, and several others stem from it.

**Comment by wphicks** [comment]
Still working on this; it's messy but tractable. There is a little bit of goofiness in terms of when overlapping elements are clicked, but that's true of the legacy system as well. Commenting now to mention that #70 will still definitely be open after this is complete.

**Comment by wphicks** [comment]
All elements of this issue resolved by latest commit. Click system is still slightly unsatisfactory in that it's not very precise, but a new issue will be opened for that.
