### ISSUE TITLE
windowing issues (not quite a reopen of #57)

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#59]
for the desktop previewer in the new system, could:
* the window be larger?
* the aspect be different (not as necessary)?
BUG (in my opinion): This window does now open corresponding to to the actual view port for the graphic world in Blender, *but*:
(at least on the Mac OSX) when the window is resized and its aspect changes black is used to 'letter-box' or side-band the view port (if vie port is the right word).
DESIRED BEHAVIOR: The window should only be resizable (if at all) with locked aspect (dragging from a corner is constrained - no letter-boxing or side-banding can occur).

**Comment by wphicks** [comment]
Ah, I understand the issue. The window can definitely be larger; the resizing issue is trickier. This would essentially require an "upstream" feature request for blenderplayer or a fancy (probably platform-dependent) hack to enforce it. That half of that will probably have to wait a bit.

What size would you like for default?

**Comment by shadoof** [comment]
That's perfectly OK. So long as the window opens, initially, with no (confusing) banding/letter-boxing (as it does now), I think that's important.

Size: for (local-system) designing that targets the Granoff Cave and while we sort out these teething problems, I think the window should be the same size as that for the current CW previewer.

Also: in the circs, can you prevent this window from being drag-resizeable?

**Comment by wphicks** [comment]
If someone can tell me the current size of the CW previewer in pixels (on Mac or Windows) that would be helpful, but it's an easy fix from there. As far as drag-resizing, that's handled by the window manager on each platform, and not even the CW previewer effectively prevents that under all configurations.

**Comment by shadoof** [comment]
@wphicks on my system's screen it seems to be 800 x 700 (sic). I have no idea why. Perhaps we could at least use 800 x 600 which would, at least. be 4:3. I have also (only just! now I 'look') noticed that the CW previewer stretches rectangles vertically. The back wall is not drawn as a square. What else is there to say about this but: wtf

**Comment by wphicks** [comment]
Haha, okay sounds good. Yes, I think 800 x 600 is the more sensible default, and that's where we'll start. I'll push that through as soon as I'm done working on the mouse click issue.

**Comment by wphicks** [comment]
Turns out I didn't know what I was talking about in terms of options available for scaling the window. This is now fixed so that you can rescale to any size you want without black bars or messing up the resolution. Window defaults to 800x600.

**Comment by shadoof** [comment]
great stuff, Will!
