### ISSUE TITLE
Vertical text alignment handled differently from legacy system

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#63]
In CW, text (and other) objects have horiz-align and vert-align properties, defaulting to "(center)".
W3D either has different defaults or interprets these differently. horiz-alignment seems OK. With respect to vert-alignment, W3D currently treats the Y position parameter as referring to the ? ascender height of the font (should refer to font height / 2).

**Comment by wphicks** [comment]
Default text alignments appear to be the same for both systems. Right now, W3D looks at the exact height of whatever text object gets created and offsets the text by half or all of that height to create centered or bottom-aligned text respectively. (Note to self: happens [here](https://github.com/wphicks/Writing3D/blob/847bebaf4745847bf71348dac29a8d09da26dbe1/pyw3d/objects.py#L429)) This is based on the actual size of the object mesh, not anything text-specific.

To clarify, does it look like CW's vertical text alignment *ignores* ascenders and descenders? Or that it always vertically aligns based on the maximum ascender-to-descender font height? Either way, replicating that will (I think) require us to create a phony ("hp" or "oo") object for each font used in the project and get the offset that way. Blender does not offer vertical text alignment on its own.

**Comment by wphicks** [comment]
Dropping the high-priority label. This may be affected by resolution of #61.

**Comment by wphicks** [comment]
Resolution of #61 does not affect this issue, so I'm going to throw a testing-needed flag on for further information about exactly what the expected behavior is. This can also be reflagged as high-priority if that seems necessary.

**Comment by wphicks** [comment]
Just uploaded sample_10_textalign to the samples drive, which should be helpful for testing.

**Comment by wphicks** [comment]
Aha! Every now and then, I realize I'm an idiot. The offset needs to be 1/4 of the font height in either direction, not 1/2, which is what @shadoof was saying to begin with. I was just being completely dense. Okay, going to push the solution now.

**Comment by wphicks** [comment]
In testing sample_14, I realized that I was right before about the default handling of text alignment. Will revert this change in addressing #80. @shadoof, once #80 is closed, will you take a look and see if the problem you were originally talking about has been addressed? In particular, sample_10 and sample_14 may be useful to look at in order to describe exactly the problem we're interested in.

**Comment by wphicks** [comment]
Ah! Now I'm seeing the issue- alignment was relative to fixed position rather than positioning being relative based on alignment. Should be able to get this (mostly) fixed up with next commit.

**Comment by wphicks** [comment]
Note that this commit *almost* but not exactly replicates the alignment behavior of cwapp. Ascenders and descenders are measured just *slightly* differently, as can be seen in sample_14. If this becomes relevant for any legacy project, please reopen this issue.
