### ISSUE TITLE
Legacy lighting system may handle lighting response flag differently

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#64]
This sample exposes differences between the two systems.
* check that behavior of *depthless* text really is the same for both setting of the "(Responds to) Lighting" (yes/no) parameter and decide on best default for W3D.
* sort out rendering issues for text-with-depth in W3D and attempt to match behavior in CW.

**Comment by wphicks** [comment]
As far as I can tell, flat text is responding as expected to lighting. If anyone is seeing a different behavior on their own system, a screenshot would be very helpful.

In terms of text with depth, the lighting provided by Blender is *far* more realistic than that provided by CW, so I expect some rendering differences. How severe is what you're seeing? We can tune the default material settings to provide less realistic reflection/shadows if necessary, but we should decide to what extent the better lighting is a feature vs a bug.

Going to swap the high-priority label for testing-needed until I see a screenshot showing inaccurate response to the "Lighting" toggle for flat text. Beyond that, we can chat about priorities for the lighting system in this thread.

**Comment by wphicks** [comment]
To test the "responds to lighting" toggle, use sample_09_fontlights and try toggling the Lighting property of the clickable links.

**Comment by wphicks** [comment]
Hmmm... sample_13 is also showing some issues with brighter extruded text than seen in default. Going to drop the testing-needed flag on this. sample_13 should be used for testing going forward.
