### ISSUE TITLE
Add installation information to Wiki

### ISSUE THREAD

**Issue by wphicks** [wphicks/Writing3D#66]
The new install method should be documented on the Wiki.

**Comment by shadoof** [comment]
@wphicks I intend to develop a w3d site at writing3d.xyz, which will be within an encompassing dlarts.xyz site. I will be using Clement Valla's Binder and embedded Google Docs for this. Could the documentation Wiki be a Google Docs page within this site? Could it be directly linked from this repo?

**Comment by shadoof** [comment]
@wphicks In fact, I've updated writing3d.xyz and its folder is shared with you, along with this first page that I've set up
```
https://docs.google.com/document/d/1oeHaqhiTu9GLZDjIt33jTtnzt7is5c6dpdsm1_VGrG8/edit?usp=sharing
```
And you could share this in turn with Pauline, etc., as and when.

**Comment by wphicks** [comment]
That looks great, @shadoof! I'm onboard with this 100%, and I'll update the repo soon to direct people that way. I think it makes sense to transition the documentation I already have on this site to be more developer-oriented and let the documentation on writing3d.xyz be more user/consumer oriented. The layout looks marvelous.

**Comment by wphicks** [comment]
@shadoof An important follow-up: Would it be all right if we hosted the install zips on that site? It would be nice to have something a little more official/stable than my Google drive.

**Comment by shadoof** [comment]
Yes @wphicks, definitely. Let's use this shared folder, making the zip accessible to 'anyone who has the link', OK? Note, this will be own my Brown University Google Drive, which I assume is OK by you?
```
https://drive.google.com/open?id=0By7izea0dXGybTNNWEhreWJpTnc
```

**Comment by wphicks** [comment]
Ah, I actually meant hosting directly on whatever server you're using for writing3d.xyz (removing the Drive dependency entirely). If it's easier to stick with Drive for now, I'm perfectly happy leaving it on my own account. I was just thinking if we ever get a *very* significant uptick in traffic, it's probably better to be hosting those files ourselves, but that is probably hopelessly optimistic.

**Comment by shadoof** [comment]
@wphicks - sure Will, no problem. Although you may have to suggest a good workflow for this. I guess either:
* you take credentials for the DreamHost site, or
* I clone (some part of?) the repo where the zips are built from the release branch into a folder that I mirror on the DreamHost site? (It is only, so far, the tiny Binder-specific files that are hosted on DreamHost)

**Comment by wphicks** [comment]
@shadoof Sounds good- I'm going to spin this off into a separate issue and think about the best workflow for this. It's probably possible to automate this so that I don't need the credentials (except for the initial setup) and you don't need to ever worry about processing updates. Let me figure that out myself, and in the meantime, people can continue to grab builds off Drive. This is definitely a low priority item.
