### ISSUE TITLE
Samples should be more accessible

### ISSUE THREAD

**Issue by wphicks** [wphicks/Writing3D#69]
This one's a primarily administrative issue. The problem is that most of those samples were done by people no longer involved with the project, and when I tried to get their permission to include them here under some sort of permissive license, I never heard back. Regardless, we need a way for new people coming onboard to access the samples and begin testing right away.

On a semi-related note, if we do make these more accessible, let's replace "Army of Darkness" as the standard test image. Not only are there licensing issues, but also it's not the best image for creating a welcoming community.

**Comment by shadoof** [comment]
Closing this since the samples are basically now by us, I've made a repo for them and the Army of Darkness images will be removed.
