### ISSUE TITLE
Implement sound in Blender

### ISSUE THREAD

**Issue by wphicks** [wphicks/Writing3D#7]

**Comment by purvigoel** [comment]
File "/Users/purvigoel/Library/Python/3.4/bin/w3d_export_tools.py", line 96, in <module>
    input_project = unpickle_w3dproject(args.project_file)
  File "/Users/purvigoel/Library/Python/3.4/bin/w3d_export_tools.py", line 38, in unpickle_w3dproject
    return pickle.load(open(filename, "rb"))
  File "/Users/purvigoel/Writing3D/pyw3d/features.py", line 71, in __setitem__
    "{} is not a valid value for option {}".format(value, key))
pyw3d.errors.InvalidArgument: ['A Wall', '2', '3', '4', '5', '6'] is not a valid value for option objects

Blender quit
Color management: using fallback mode for management
BLT_lang_init: 'locale' data path for translations not found, continuing
ndof: 3Dx driver not found

usage:   /Users/purvigoel/Writing3D/blender-2.76-OSX_10.6-x86_64/blenderplayer.app/Contents/MacOS/blenderplayer [--options] filename.blend

Available options are: [-w [w h l t]] [-f [fw fh fb ff]] [-g gamengineoptions] [-s stereomode] [-m aasamples]
Optional parameters must be passed in order.
Default values are set in the blend file.

  -h: Prints this command summary

  -w: display in a window
       --Optional parameters--
       w = window width
       h = window height
       l = window left coordinate
       t = window top coordinate
       Note: To define 'w' or 'h', both must be used.Also, to define 'l' or 't', all four parameters must be used.
       Example: -w   or  -w 500 300  or  -w 500 300 0 0

  -f: start game in fullscreen mode
       --Optional parameters--
       fw = fullscreen mode pixel width    (use 0 to detect automatically)
       fh = fullscreen mode pixel height   (use 0 to detect automatically)
       fb = fullscreen mode bits per pixel (default unless set in the blend file: 32)
       ff = fullscreen mode frequency      (default unless set in the blend file: 60)
       Note: To define 'fw'' or 'fh'', both must be used.
       Example: -f  or  -f 1024 768  or  -f 0 0 16  or  -f 1024 728 16 30

  -s: start player in stereoscopy mode (requires 3D capable hardware)
       stereomode: nostereo         (default unless stereo is set in the blend file)
                   anaglyph         (Red-Blue glasses)
                   sidebyside       (Left Right)
                   syncdoubling     (Above Below)
                   3dtvtopbottom    (Squashed Top-Bottom for passive glasses)
                   interlace        (Interlace horizontally)
                   vinterlace       (Vertical interlace for autostereo display)
                   hwpageflip       (Quad buffered shutter glasses)
       Example: -s sidebyside  or  -s vinterlace

  -D: start player in dome mode
       --Optional parameters--
       angle    = field of view in degrees
       tilt     = tilt angle in degrees
       warpdata = a file to use for warping the image (absolute path)
       mode: fisheye                (Fisheye)
             truncatedfront         (Front-Truncated)
             truncatedrear          (Rear-Truncated)
             cubemap                (Cube Map)
             sphericalpanoramic     (Spherical Panoramic)
       Example: -D  or  -D mode cubemap

  -m: maximum anti-aliasing (eg. 2,4,8,16)

  -i: parent window's ID

  -d: turn debugging on

  -g: game engine options:

       Name                       Default      Description
       ------------------------------------------------------------------------
       fixedtime                      0         "Enable all frames"
       nomipmap                       0         Disable mipmaps
       show_framerate                 0         Show the frame rate
       show_properties                0         Show debug properties
       show_profile                   0         Show profiling information
       blender_material               0         Enable material settings
       ignore_deprecation_warnings    1         Ignore deprecation warnings

  - : all arguments after this are ignored, allowing python to access them from sys.argv

example: /Users/purvigoel/Writing3D/blender-2.76-OSX_10.6-x86_64/blenderplayer.app/Contents/MacOS/blenderplayer -w 320 200 10 10 -g noaudio /home/user/filename.blend
example: /Users/purvigoel/Writing3D/blender-2.76-OSX_10.6-x86_64/blenderplayer.app/Contents/MacOS/blenderplayer -g show_framerate = 0 /home/user/filename.blend
example: /Users/purvigoel/Writing3D/blender-2.76-OSX_10.6-x86_64/blenderplayer.app/Contents/MacOS/blenderplayer -i 232421 -m 16 /home/user/filename.blend

**Comment by wphicks** [comment]
Resolved by 360d0a2da0a9b748c4b8d772b28fca503660df39.
