### ISSUE TITLE
check rotations and also horizontal and vertical alignment for sample_09_frontlights.xml

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#96]

**Comment by wphicks** [comment]
Darn, this is a result of #71. Clicks are just activating several of the links simultaneously. I'll see what I can do. @shadoof, I'm not sure exactly what issue you're seeing in terms of alignment. Could you describe a bit more or upload an image?

Sample 16 is the most rigorous vertical alignment test I'm aware of among our samples. Are you seeing problems with that one, too?

**Comment by shadoof** [comment]
@wphicks I'm not checking with Sample 16, as yet. I see that the problems are at least exacerbated by the triggering of multiple links (active areas of text objects are overlapping? -- which may be a product of this default font's strangely large point size?)
  The 'R' in the default Bfont seems to me to be ranging left and to have a Y-axis that is, as it were to the right of the 'R' rather than in its visual center. Whereas the (Courier) default in CW is center-aligned in the way that I would expect. Images uploading ...
![screen shot 2017-09-18 at 10 51 08 am](https://user-images.githubusercontent.com/1051808/30548147-5f4e22e6-9c5f-11e7-8588-66570b3f5252.jpg)
![screen shot 2017-09-18 at 10 50 45 am](https://user-images.githubusercontent.com/1051808/30548148-5f64129a-9c5f-11e7-954e-9848acda75da.jpg)
![screen shot 2017-09-18 at 10 50 02 am](https://user-images.githubusercontent.com/1051808/30548149-5f64f8b8-9c5f-11e7-97c4-6fb48f7d100b.jpg)
![screen shot 2017-09-18 at 10 49 19 am](https://user-images.githubusercontent.com/1051808/30548150-5f69bdf8-9c5f-11e7-8119-0dae92f08a5c.jpg)

**Comment by wphicks** [comment]
Ah, I see! I understand the axis issue and should be able to fix it. I'm working on getting the click situation fixed up first, but I'll take care of that next. Thanks very much for the details and screenshot.

**Comment by wphicks** [comment]
Accidental closing- don't read anything into that.

**Comment by wphicks** [comment]
May actually be corrected by necessary changes in the upgrade to Blender 2.79 (see #102).

**Comment by shadoof** [comment]
@hphicks Still needs work see #102 Multiple nearby (on the Y axis anyway) links are evoked by a single click. Especially, in this sample, clicking on a link underneath tends to trigger the link above.

**Comment by wphicks** [comment]
Roger that. Is the issue now *just* the multiple clicks, or is there still an issue around alignment?

**Comment by shadoof** [comment]
* Multiple clicks was the main issue. (I have been altering the project for teaching and test purposes. The click-broken version would have to be reconstituted - by closing Y-space between link text to 0.5)
* Alignment needs checking but alignment problem was only really noticeable with the Blender default font. (Once Courier_New_Bold became the default alignment seems good.)

**Comment by wphicks** [comment]
Okay, great! In that case, I'm going to merge this with #71. It sounds like that should probably be moved up to high priority, but I'll let you do that on your own judgement (not sure if there are other issues that are higher up the food chain).

**Comment by wphicks** [comment]
Tested this sample with the commit closing #71 and confirmed that it is working as expected.
